# NOTE: this is not the environment.yml used to build docker images. changes
# here will NOT be reflected in future docker builds. see the environment.yml
# file in the "docker" folder for changes that need to go into the docker
# image (only the libs needed by the ETL code should be put in there.)
#
name: heavyai_deploy
channels:
- conda-forge
- defaults
dependencies:

- python = 3.11

- pandas
- pyarrow
- numpy
- thrift

# aws
- boto3
- boto3-stubs

# testing
- icecream
- pytest

# workflow
- python-dotenv

# heavyai
- heavyai = 1.3
- sqlalchemy
- sqlalchemy-heavyai
- sqlparse
