CREATE FOREIGN TABLE IF NOT EXISTS XXTNAMEXX (
    longitude FLOAT,
    latitude FLOAT,
    h3_06 TEXT ENCODING DICT(32),
    h3_06i BIGINT,
    huc12 TEXT ENCODING DICT(32),
    huc8 TEXT ENCODING DICT(16),
    cbg_fips TEXT ENCODING DICT(32),
    state_fips TEXT ENCODING DICT(8),
    county_fips TEXT ENCODING DICT(16),
    model_ts TIMESTAMP(0) ENCODING FIXED(32),
    model_ts_str TEXT ENCODING DICT(32),
    forecast_ts TIMESTAMP(0) ENCODING FIXED(32),
    forecast_hour INTEGER,
    Wind_Gust_10m_MPS FLOAT,
    Wind_Gust_10m_MPH FLOAT,
    Wind_Speed_10m_MPS FLOAT,
    Wind_Speed_10m_MPH FLOAT,
    Wind_Direction_10m FLOAT,
    Wind_Speed_80m_MPS FLOAT,
    Wind_Speed_80m_MPH FLOAT,
    Wind_Direction_80m FLOAT,
    Peak_Gust_Swath_MPS FLOAT,
    Peak_Gust_Swath_MPH FLOAT,
    Dew_Point_2m_C FLOAT,
    Dew_Point_2m_F FLOAT,
    Dew_Point_Depression_2m_C FLOAT,
    Dew_Point_Depression_2m_F FLOAT,
    Relative_Humidity_2m FLOAT,
    Air_Temperature_2m_C FLOAT,
    Air_Temperature_2m_F FLOAT,
    Mixing_Ratio_2m_GPKg FLOAT,
    Precipitation__Interval_In FLOAT,
    Precipitation__Interval_mm SMALLINT,
    Precipitation__Accumulated_In FLOAT,
    Precipitation__Accumulated_mm SMALLINT,
    Precipitation_Type_Flag TEXT ENCODING DICT(8),
    Rain__Interval_In FLOAT,
    Rain__Interval_mm SMALLINT,
    Rain__Accumulated_In FLOAT,
    Rain__Accumulated_mm SMALLINT,
    Snow_Water_Equivalent__Interval_In FLOAT,
    Snow_Water_Equivalent__Interval_mm SMALLINT,
    Snow_Water_Equivalent__Accumulated_In FLOAT,
    Snow_Water_Equivalent__Accumulated_mm SMALLINT,
    Snow_Total_In FLOAT,
    Snow_Total_mm SMALLINT,
    Freezing_Rain__Interval_In FLOAT,
    Freezing_Rain__Interval_mm SMALLINT,
    Freezing_Rain__Accumulated_In FLOAT,
    Freezing_Rain__Accumulated_mm SMALLINT,
    Sleet__Interval_In FLOAT,
    Sleet__Interval_mm SMALLINT,
    Sleet__Accumulated_In FLOAT,
    Sleet__Accumulated_mm SMALLINT,
    Cloud_Cover_Low FLOAT,
    Cloud_Cover_Medium FLOAT,
    Cloud_Cover_High FLOAT,
    Total_Cloud_Cover FLOAT,
    Isobaric_Level_Absolute_Vorticity FLOAT,
    Pressure_1000_850_MB_Thickness_Dm FLOAT,
    Pressure_850_700_MB_Thickness_Dm FLOAT,
    Pressure_850_500_MB_Thickness_Dm FLOAT,
    Pressure_1000_500_MB_Thickness_Dm FLOAT,
    Lifted_Index_C FLOAT,
    Convective_Available_Potential_Energy__CAPE_JPKg FLOAT,
    Most_Unstable_CAPE_JPKg FLOAT,
    Precipitable_Water_In FLOAT,
    Precipitable_Water_mm SMALLINT,
    Total_Totals_Index_C FLOAT,
    Solar_Insolation_WpM2 FLOAT,
    Vapor_Pressure_Deficit_Kpa FLOAT,
    Lightning FLOAT
)
SERVER XXSERVERXX
XXWITH_CLAUSEXX;